### ISSUE TITLE
Protein signaling network dataset link

### ISSUE THREAD

**Issue by sobalgi** [AWehenkel/DAG-NF#2]
Hi,

Can you please point me towards the dataset of the protein signaling network experiment?

I see in the datasets 'X_train.pkt' file is mentioned.
But I don't seems to find the pkt file with the downloaded UCIdatasets.

Please let me know if I'm missing something.

**Comment by AWehenkel** [comment]
Hi, 
You're right, the proteins signalling network experiment is not part of the UCI datasets. I just uploaded the files that were missing from the repo.
Let me know if something else is missing.
Best,
Antoine

**Comment by sobalgi** [comment]
Hello Antoine (@AWehenkel ),

Thanks for the uploads.
I was able to download the dataset files.
I'll shortly try to run the code.

A small observation in proteins.py regarding the train data being reloaded as validation data instead of actual validation data.

https://github.com/AWehenkel/Graphical-Normalizing-Flows/blob/9d03b7b3ee470cc1c69aefba1d660d6fc5a3290c/UCIdatasets/proteins.py#L70

`    valid = torch.load(dir_f + "X_valid.pkt")` should fix it I guess.

Best,
SB.
